controller_list:
  - name: fake_kanan_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint4
      - Joint6
      - Joint8
      - Joint10
      - Joint12
      - Joint14
  - name: fake_kiri_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint3
      - Joint5
      - Joint7
      - Joint9
      - Joint11
      - Joint13
  - name: fake_badan_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint5
      - Joint7
      - Joint9
      - Joint11
      - Joint13
      - Joint4
      - Joint6
      - Joint8
      - Joint10
      - Joint12
      - Joint14
initial:  # Define initial robot poses per group
  - group: kanan
    pose: berdiri
  - group: kiri
    pose: berdiri