controller_list:
  - name: kanan_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Joint4
      - Joint6
      - Joint8
      - Joint10
      - Joint12
      - Joint14
  - name: kiri_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Joint3
      - Joint5
      - Joint7
      - Joint9
      - Joint11
      - Joint13
  - name: badan_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint5
      - Joint7
      - Joint9
      - Joint11
      - Joint13
      - Joint4
      - Joint6
      - Joint8
      - Joint10
      - Joint12
      - Joint14